# require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# platform :ios, '10.0'

# target 'Wuduplz' do
#   config = use_native_modules!

#   use_react_native!(:path => config["reactNativePath"])

#   pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

#   pod 'react-native-video', :path => '../node_modules/react-native-video'


#   pod 'react-native-camera', :path => '../node_modules/react-native-camera'

#   target 'WuduplzTests' do
#     inherit! :complete
#     # Pods for testing
#   end

#   # Enables Flipper.
#   #
#   # Note that if you have use_frameworks! enabled, Flipper will not work and
#   # you should disable these next few lines.
#   use_flipper!
#   post_install do |installer|
#     flipper_post_install(installer)
#   end
# end

# target 'Wuduplz-tvOS' do
#   # Pods for Wuduplz-tvOS

#   target 'Wuduplz-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end


require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Wuduplz' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-video', :path => '../node_modules/react-native-video'


  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-ffmpeg', :path => '../node_modules/react-native-ffmpeg'

  target 'WuduplzTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Wuduplz-tvOS' do
  # Pods for Wuduplz-tvOS

  target 'Wuduplz-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
